// Seed data and mock store for offline and demo development

export const INITIAL_CATEGORIES = [
  { id: 1, name: 'Pothole / Roadway', icon: 'pothole', department: 'Dept of Transportation' },
  { id: 2, name: 'Streetlight & Power', icon: 'streetlight', department: 'Bureau of Public Lighting' },
  { id: 3, name: 'Stormwater Drainage', icon: 'drainage', department: 'Water & Sewerage Authority' },
  { id: 4, name: 'Solid Waste & Garbage', icon: 'garbage', department: 'Waste Management Bureau' },
  { id: 5, name: 'Water Main Leak', icon: 'water-leak', department: 'Municipal Water Board' },
  { id: 6, name: 'Public Facility & Parks', icon: 'facility', department: 'Parks & Public Works' },
];

export const INITIAL_AREAS = [
  { id: 1, name: 'Ward 4 - Metro East', code: 'W04', population: '84,200', openIssues: 18 },
  { id: 2, name: 'Ward 2 - Westlands', code: 'W02', population: '92,100', openIssues: 12 },
  { id: 3, name: 'Ward 5 - Kilimani', code: 'W05', population: '78,400', openIssues: 9 },
  { id: 4, name: 'Ward 1 - Central CBD', code: 'W01', population: '110,000', openIssues: 24 },
  { id: 5, name: 'Ward 7 - Industrial Corridor', code: 'W07', population: '62,500', openIssues: 15 },
  { id: 6, name: 'Ward 3 - Parklands North', code: 'W03', population: '71,300', openIssues: 8 },
];

export const DEMO_USERS = [
  {
    id: 1,
    name: 'Sarah Jenkins',
    email: 'resident@civicpulse.org',
    role: 'resident',
    area_id: 1,
    phone: '+1 (555) 234-8901',
    trustScore: 98.4,
    tier: 'Tier V - Master Sentinel',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=256',
    memberSince: 'Oct 2021',
    civicXP: 980,
  },
  {
    id: 2,
    name: 'J. Ramirez (Lead Verifier)',
    email: 'verifier@civicpulse.org',
    role: 'verifier',
    area_id: 1,
    phone: '+1 (555) 789-1122',
    trustScore: 99.2,
    tier: 'Senior Triage Officer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
    memberSince: 'Jan 2020',
    civicXP: 2450,
  },
  {
    id: 3,
    name: 'Alex Chen (Crew 4B Dispatch)',
    email: 'authority@civicpulse.org',
    role: 'authority',
    area_id: 1,
    phone: '+1 (555) 432-8877',
    trustScore: 97.9,
    tier: 'Field Superintendent',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
    memberSince: 'Mar 2019',
    civicXP: 3100,
  },
  {
    id: 4,
    name: 'Marcus Vance (City Commissioner)',
    email: 'admin@civicpulse.org',
    role: 'admin',
    area_id: 1,
    phone: '+1 (555) 998-3344',
    trustScore: 100,
    tier: 'System Administrator',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=256',
    memberSince: 'Nov 2018',
    civicXP: 5000,
  },
];

export const INITIAL_REPORTS = [
  {
    id: 9421,
    category: INITIAL_CATEGORIES[0],
    description: 'Deep road fissure and pothole on East Birch & 14th Ave expanding across pedestrian crosswalk curb edge. Water accumulation creates collision risk during morning bus transit.',
    status: 'in_progress',
    location: { lat: -1.2629, lon: 36.8355 },
    address: '1420 E Birch Ave, Metro East',
    landmark: 'Opposite Shell Fuel Station & Crosswalk',
    area_id: 1,
    photo_url: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=800',
    created_by: 1,
    creator_name: 'Sarah Jenkins',
    assigned_to: 3,
    assigned_name: 'Alex Chen (Crew 4B Dispatch)',
    due_date: '2026-10-15',
    report_count: 42,
    duplicate_of: null,
    ai_suggested_category: { category_id: 1, confidence: 0.94 },
    is_following: true,
    created_at: '2026-09-24T08:30:00Z',
    updated_at: '2026-10-02T11:15:00Z',
  },
  {
    id: 8902,
    category: INITIAL_CATEGORIES[4],
    description: 'High-pressure mainline water pipe leakage near Metro Park South. Hydrant valve rupture leaking potable water into storm drains. Repaired by Metro Water crew.',
    status: 'resolved',
    location: { lat: -1.2580, lon: 36.8210 },
    address: '842 Maple Ave, Ward 4',
    landmark: 'Near Metro Park Entrance',
    area_id: 1,
    photo_url: 'https://images.unsplash.com/photo-1584824486509-112e4181ff6b?auto=format&fit=crop&q=80&w=800',
    created_by: 1,
    creator_name: 'Sarah Jenkins',
    assigned_to: 3,
    assigned_name: 'Alex Chen (Crew 4B Dispatch)',
    due_date: '2026-09-20',
    report_count: 19,
    duplicate_of: null,
    ai_suggested_category: { category_id: 5, confidence: 0.98 },
    is_following: true,
    created_at: '2026-09-18T14:20:00Z',
    updated_at: '2026-09-19T10:45:00Z',
  },
  {
    id: 7739,
    category: INITIAL_CATEGORIES[2],
    description: 'Stormwater drainage overflow at 6th St culvert. Plastic rubbish and silt blocking primary conduit after heavy rainfall.',
    status: 'reported',
    location: { lat: -1.2490, lon: 36.7921 },
    address: '482 Oak Street, Near Corner of 4th Ave',
    landmark: 'Directly opposite the public transit stop shelter',
    area_id: 1,
    photo_url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=800',
    created_by: 1,
    creator_name: 'Sarah Jenkins',
    assigned_to: null,
    assigned_name: null,
    due_date: null,
    report_count: 5,
    duplicate_of: null,
    ai_suggested_category: { category_id: 3, confidence: 0.89 },
    is_following: false,
    created_at: '2026-10-08T09:14:00Z',
    updated_at: '2026-10-08T09:14:00Z',
  },
  {
    id: 6412,
    category: INITIAL_CATEGORIES[1],
    description: 'Broken overhead streetlight pole outside Lincoln Elementary. Blinking violently at night creating dark hazards for students.',
    status: 'verified',
    location: { lat: -1.2750, lon: 36.8120 },
    address: '742 Evergreen Terrace, Ward 2',
    landmark: 'Lincoln Elementary School Gate B',
    area_id: 2,
    photo_url: 'https://images.unsplash.com/photo-1508873696983-2df5293cb395?auto=format&fit=crop&q=80&w=800',
    created_by: 1,
    creator_name: 'Sarah Jenkins',
    assigned_to: null,
    assigned_name: null,
    due_date: null,
    report_count: 12,
    duplicate_of: null,
    ai_suggested_category: { category_id: 2, confidence: 0.95 },
    is_following: true,
    created_at: '2026-10-04T19:00:00Z',
    updated_at: '2026-10-05T09:30:00Z',
  },
  {
    id: 5219,
    category: INITIAL_CATEGORIES[3],
    description: 'Illegal dumping and overflowing dumpster near Community Market alleyway. Strong odors and vermin attraction.',
    status: 'assigned',
    location: { lat: -1.2830, lon: 36.8400 },
    address: 'Market Alley Way, Ward 1',
    landmark: 'Back of City Market Hall',
    area_id: 4,
    photo_url: 'https://images.unsplash.com/photo-1605600659908-0ef719419d41?auto=format&fit=crop&q=80&w=800',
    created_by: 1,
    creator_name: 'Sarah Jenkins',
    assigned_to: 3,
    assigned_name: 'Alex Chen (Crew 4B Dispatch)',
    due_date: '2026-10-12',
    report_count: 8,
    duplicate_of: null,
    ai_suggested_category: { category_id: 4, confidence: 0.91 },
    is_following: true,
    created_at: '2026-10-03T11:10:00Z',
    updated_at: '2026-10-06T14:00:00Z',
  },
  {
    id: 4109,
    category: INITIAL_CATEGORIES[0],
    description: 'Traffic signal failure at East Parkway intersection causing massive gridlock during peak hours.',
    status: 'in_progress',
    location: { lat: -1.2700, lon: 36.8280 },
    address: 'East Parkway & 5th Ave',
    landmark: 'Metro Hospital Junction',
    area_id: 1,
    photo_url: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&q=80&w=800',
    created_by: 2,
    creator_name: 'J. Ramirez',
    assigned_to: 3,
    assigned_name: 'Alex Chen (Crew 4B Dispatch)',
    due_date: '2026-10-10',
    report_count: 27,
    duplicate_of: null,
    ai_suggested_category: { category_id: 1, confidence: 0.88 },
    is_following: true,
    created_at: '2026-10-07T07:15:00Z',
    updated_at: '2026-10-08T08:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 1,
    report_id: 8902,
    type: 'hazard_dispatched',
    badge: 'Hazard Dispatched',
    ref: '#CP-4912',
    title: 'Severe Water Main Leak',
    message: 'Unit Crew 4B has arrived on site at 842 Maple Ave. Estimated resolution: 1h 45m. Water pressure drop isolated to lower sector.',
    read: false,
    created_at: '2026-10-08T10:14:00Z',
    assigned: 'Unit Crew 4B',
    priority: 'Critical / Tier 1',
    estTime: '1h 45m',
    group: 'Water Infrastructure',
  },
  {
    id: 2,
    report_id: 6412,
    type: 'report_verified',
    badge: 'Report Verified',
    ref: '#CP-4908',
    title: 'Pothole on 742 Evergreen Terrace',
    message: 'Upvoted by 19 neighbors and verified by Municipal Verifier J. Ramirez. Scheduled for asphalt patching.',
    read: false,
    created_at: '2026-10-08T09:36:00Z',
    assigned: 'Roads Dept',
    priority: 'Normal',
    estTime: '24 hours',
    group: 'Transportation',
  },
  {
    id: 3,
    report_id: null,
    type: 'ward_announcement',
    badge: 'Ward Announcement',
    ref: '#WA-108',
    title: 'Ward 4 Road Resurfacing Notice',
    message: 'Scheduled maintenance on Elm St starting tomorrow 08:00 EST. Bus routes 14 and 22 rerouted through South Avenue.',
    read: false,
    created_at: '2026-10-08T08:28:00Z',
    assigned: 'City Council',
    priority: 'Informational',
    estTime: '3 days',
    group: 'Transit Authority',
  },
  {
    id: 4,
    report_id: 8902,
    type: 'resolved',
    badge: 'Resolved',
    ref: '#CP-4892',
    title: 'Broken Streetlight outside Lincoln Elementary',
    message: 'Work order completed by Bureau of Public Lighting. Before & after photos uploaded and approved.',
    read: true,
    created_at: '2026-10-07T17:40:00Z',
    assigned: 'Bureau of Lighting',
    priority: 'Low',
    estTime: 'Completed',
    group: 'Electrical Services',
  },
];

export const INITIAL_HOTSPOTS = [
  {
    id: 1,
    center: { lat: -1.2629, lon: 36.8355 },
    radius_m: 250,
    report_count: 38,
    top_category_id: 1,
    name: 'East Birch Corridor Hotspot',
    severity: 'High',
  },
  {
    id: 2,
    center: { lat: -1.2490, lon: 36.7921 },
    radius_m: 180,
    report_count: 22,
    top_category_id: 3,
    name: 'Oak & 4th Stormwater Cluster',
    severity: 'Critical',
  },
  {
    id: 3,
    center: { lat: -1.2830, lon: 36.8400 },
    radius_m: 200,
    report_count: 19,
    top_category_id: 4,
    name: 'Market Alley Waste Hotspot',
    severity: 'Moderate',
  },
];
